"""
Author: silencesoup silencesoup@outlook.com
Date: 2024-08-29 10:41:42
LastEditors: silencesoup silencesoup@outlook.com
LastEditTime: 2024-09-02 16:58:35
FilePath: /hydroevaluate/tests/test_heutils.py
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
"""

import numpy as np
import pandas as pd
from hydroevaluate.utils.heutils import (
    calculate_nse,
    gee_gpm_to_1h_data,
    plot_time_series,
)
import os
from loguru import logger


def test_gee_single_basin_gpm_to_1h_data(tmp_path="data/gee_gpm"):
    # Create a temporary CSV file as if it is generated by gee
    csv_path = os.path.join(tmp_path, "test_data.csv")
    data = pd.DataFrame(
        {
            "time_start": pd.date_range(start="2022-01-01", periods=10, freq="30T"),
            "precipitationCal": [0.5, 0.8, 1.2, 0.3, 0.6, 0.9, 1.5, 0.7, 0.4, 1.0],
        }
    )
    logger.info(f"Orignal Data: {data}")
    csv_folder = os.path.dirname(csv_path)
    # sourcery skip: no-conditionals-in-tests
    if not os.path.exists(csv_folder):
        os.makedirs(csv_folder)
    data.to_csv(csv_path, index=False)

    # Call the gee_gpm_to_1h_data function
    result = gee_gpm_to_1h_data(csv_path)
    logger.warning(f"Processed GPM: {result}")

    # Perform assertions to validate the result
    assert isinstance(result, pd.DataFrame)


def test_nse_cal(
    observed_csv=os.path.join("data", "gee_gpm_1h", "observed.csv"),
    simulated_csv=os.path.join("data", "postgres_gpm", "simulated.csv"),
    column_name="tp",
):

    # Create sample data for observed and simulated values
    observed_data = pd.DataFrame(
        {
            "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
            "tp": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
        }
    )
    simulated_data = pd.DataFrame(
        {
            "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
            "tp": [1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2, 9.2, 10.2],
        }
    )

    # Save the sample data to CSV files
    observed_data.to_csv(observed_csv, index=False)
    simulated_data.to_csv(simulated_csv, index=False)

    # Call the calculate_nse function
    nse = calculate_nse(observed_csv, simulated_csv, column_name)

    # Perform assertion to validate the result
    assert isinstance(nse, float)
    print(nse)


def test_nse_with_local_csv():
    observed_csv = "data/gee_gpm_1h/21110400.csv"
    simulated_csv = "data/gee_gfs_1h/21110400.csv"
    column_name = "tp"
    nse = calculate_nse(observed_csv, simulated_csv, column_name)
    print(nse)


def test_plot_with_local_csv():
    plot_time_series(
        "data/gee_gpm_3h/21110400.csv", "data/station_tp/21110400.csv", "tp"
    )


import pytest
import xarray as xr
from hydroevaluate.utils.heutils import convert_units
import numpy as np
import pandas as pd
from hydroevaluate.utils.heutils import _trans_norm


def test_gee_single_basin_gpm_to_1h_data(tmp_path="data/gee_gpm"):
    # Create a temporary CSV file as if it is generated by gee
    csv_path = os.path.join(tmp_path, "test_data.csv")
    data = pd.DataFrame(
        {
            "time_start": pd.date_range(start="2022-01-01", periods=10, freq="30T"),
            "precipitationCal": [0.5, 0.8, 1.2, 0.3, 0.6, 0.9, 1.5, 0.7, 0.4, 1.0],
        }
    )
    logger.info(f"Orignal Data: {data}")
    csv_folder = os.path.dirname(csv_path)
    # sourcery skip: no-conditionals-in-tests
    if not os.path.exists(csv_folder):
        os.makedirs(csv_folder)
    data.to_csv(csv_path, index=False)

    # Call the gee_gpm_to_1h_data function
    result = gee_gpm_to_1h_data(csv_path)
    logger.warning(f"Processed GPM: {result}")

    # Perform assertions to validate the result
    assert isinstance(result, pd.DataFrame)


def test_nse_cal(
    observed_csv=os.path.join("data", "gee_gpm_1h", "observed.csv"),
    simulated_csv=os.path.join("data", "postgres_gpm", "simulated.csv"),
    column_name="tp",
):

    # Create sample data for observed and simulated values
    observed_data = pd.DataFrame(
        {
            "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
            "tp": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
        }
    )
    simulated_data = pd.DataFrame(
        {
            "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
            "tp": [1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2, 9.2, 10.2],
        }
    )

    # Save the sample data to CSV files
    observed_data.to_csv(observed_csv, index=False)
    simulated_data.to_csv(simulated_csv, index=False)

    # Call the calculate_nse function
    nse = calculate_nse(observed_csv, simulated_csv, column_name)

    # Perform assertion to validate the result
    assert isinstance(nse, float)
    print(nse)


def test_nse_with_local_csv():
    observed_csv = "data/gee_gpm_1h/21110400.csv"
    simulated_csv = "data/gee_gfs_1h/21110400.csv"
    column_name = "tp"
    nse = calculate_nse(observed_csv, simulated_csv, column_name)
    print(nse)


def test_plot_with_local_csv():
    plot_time_series(
        "data/gee_gpm_1h/observed.csv", "data/postgres_gpm/simulated.csv", "tp"
    )


def test_convert_units():
    # Create sample data
    ds = xr.Dataset(
        {
            "precipitation": (("time", "lat", "lon"), np.random.rand(10, 5, 5)),
            "streamflow": (("time", "lat", "lon"), np.random.rand(10, 5, 5)),
        }
    )

    units = {"precipitation": ("mm/h", "mm/3h"), "streamflow": ("ft^3/s", "mm/h")}

    area = 1000  # Assume the area is 1000 square meters
    ds_converted = convert_units(ds, units, area)
    print(ds_converted)


def test_trans_norm():
    # Create sample data
    data = xr.DataArray(
        np.random.rand(10, 3),
        dims=["time", "variable"],
        coords={
            "time": pd.date_range("2022-01-01", periods=10),
            "variable": ["var1", "var2", "var3"],
        },
    )

    var_lst = ["var1", "var2", "var3"]
    stat_dict = {
        "var1": [None, None, 0.5, 0.1],
        "var2": [None, None, 0.6, 0.2],
        "var3": [None, None, 0.7, 0.3],
    }
    log_norm_cols = ["var2"]

    # Test normalization
    normalized_data = _trans_norm(data, var_lst, stat_dict, log_norm_cols, to_norm=True)
    assert isinstance(normalized_data, xr.DataArray)
    assert normalized_data.shape == data.shape

    # Test denormalization
    denormalized_data = _trans_norm(
        normalized_data, var_lst, stat_dict, log_norm_cols, to_norm=False
    )
    assert isinstance(denormalized_data, xr.DataArray)
    assert denormalized_data.shape == data.shape

    # Check if the denormalized data is close to the original data
    np.testing.assert_allclose(data, denormalized_data, rtol=1e-5)


def test_trans_norm_with_none_input():
    result = _trans_norm(None, [], {})
    assert result is None


def test_trans_norm_with_empty_var_lst():
    data = xr.DataArray(
        np.random.rand(10, 3),
        dims=["time", "variable"],
        coords={
            "time": pd.date_range("2022-01-01", periods=10),
            "variable": ["var1", "var2", "var3"],
        },
    )
    result = _trans_norm(data, [], {})
    assert result is not None
    assert result.shape == data.shape


def test_trans_norm_with_str_var_lst():
    data = xr.DataArray(
        np.random.rand(10, 1),
        dims=["time", "variable"],
        coords={"time": pd.date_range("2022-01-01", periods=10), "variable": ["var1"]},
    )
    var_lst = "var1"
    stat_dict = {"var1": [None, None, 0.5, 0.1]}
    result = _trans_norm(data, var_lst, stat_dict)
    assert result is not None
    assert result.shape == data.shape
