'''
Author: silencesoup silencesoup@outlook.com
Date: 2024-08-29 10:41:42
LastEditors: silencesoup silencesoup@outlook.com
LastEditTime: 2024-08-30 14:35:23
FilePath: /hydroevaluate/tests/test_heutils.py
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
'''
import pandas as pd
from hydroevaluate.utils.heutils import calculate_nse, gee_gpm_to_1h_data, plot_time_series
import os
from loguru import logger

def test_gee_single_basin_gpm_to_1h_data(tmp_path = 'data/gee_gpm'):
    # Create a temporary CSV file as if it is generated by gee
    csv_path = os.path.join(tmp_path, "test_data.csv")
    data = pd.DataFrame({
        "time_start": pd.date_range(start="2022-01-01", periods=10, freq="30T"),
        "precipitationCal": [0.5, 0.8, 1.2, 0.3, 0.6, 0.9, 1.5, 0.7, 0.4, 1.0]
    })
    logger.info(f"Orignal Data: {data}")
    csv_folder = os.path.dirname(csv_path)
    # sourcery skip: no-conditionals-in-tests
    if not os.path.exists(csv_folder):
        os.makedirs(csv_folder)
    data.to_csv(csv_path, index=False)
    
    # Call the gee_gpm_to_1h_data function
    result = gee_gpm_to_1h_data(csv_path)
    logger.warning(f"Processed GPM: {result}")
    
    # Perform assertions to validate the result
    assert isinstance(result, pd.DataFrame)
    
def test_nse_cal(
    observed_csv = os.path.join('data','gee_gpm_1h',"observed.csv"),
    simulated_csv = os.path.join('data', 'postgres_gpm',"simulated.csv"),
    column_name = 'tp'
    ):

    # Create sample data for observed and simulated values
    observed_data = pd.DataFrame({
        "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
        "tp": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
    })
    simulated_data = pd.DataFrame({
        "time": pd.date_range(start="2022-01-01", periods=10, freq="h"),
        "tp": [1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2, 9.2, 10.2]
    })

    # Save the sample data to CSV files
    observed_data.to_csv(observed_csv, index=False)
    simulated_data.to_csv(simulated_csv, index=False)

    # Call the calculate_nse function
    nse = calculate_nse(observed_csv, simulated_csv, column_name)

    # Perform assertion to validate the result
    assert isinstance(nse, float)
    print(nse)

def test_nse_with_local_csv():
    observed_csv = 'data/gee_gpm_1h/21110400.csv'
    simulated_csv = 'data/gee_gfs_1h/21110400.csv'
    column_name = 'tp'
    nse = calculate_nse(observed_csv, simulated_csv, column_name)
    print(nse)
    
def test_plot_with_local_csv():
    plot_time_series('data/gee_gpm_3h/21110400.csv', 'data/station_tp/21110400.csv', 'tp')